# Generated by Django 3.2.8 on 2021-10-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
    ]
