# Generated by Django 3.2.8 on 2021-10-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20211019_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(default='avatar.png', upload_to='avatars/'),
        ),
    ]
